    name: auto-test

    on:
        - push

    jobs:
        build:
            runs-on: ubuntu-latest
            strategy:
                matrix:
                    python-version: [3.12]

            steps:
              - uses: actions/checkout@v3

              - name: setup-pyhton
                uses: actions/setup-python@v4
                with:
                  python-version: ${{matrix.python-version}}
